spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/traveloop
spring.datasource.username=root
spring.datasource.password=Rithish4452K

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080